### ISSUE TITLE
detect sequence of digits

### ISSUE THREAD

**Issue by raymond1985** [stevenobadja/math_object_detection#1]
Hi Steven, 
since ssd can handle simple math operators, I think it can also detect and recognize sequence of hand-writing digits. 

I am  just wondering the possibility of this, hope you can give me some suggestion.

**Comment by stevenobadja** [comment]
Hey Raymond,

Sorry for the late reply, I haven't been on much lately. To answer your question, this model does both math operators and handwritten digits. On the video demo, it solves the equation that is written on the board. What I'm trying to do next is have it recognize the placement of numbers (e.g. exponentials and division where the number is below or above)
